# Generated by Django 5.2.8 on 2025-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='is_like',
        ),
        migrations.AddField(
            model_name='postlike',
            name='reaction',
            field=models.CharField(choices=[('none', 'No Reaction'), ('like', 'Like'), ('dislike', 'Dislike')], default='none', max_length=10),
        ),
    ]
